solve the linear algebra system

In [2]:
import numpy as np

In [5]:
A = [[4, 6, 2],
     [3, 4, 1],
     [2, 8, 13]]

s = [9, 7, 2]

r = np.linalg.solve(A, s)

r

array([ 3.00000000e+00, -5.00000000e-01, -1.98254112e-17])

Calculating the inverse a the matrix

In [8]:
A = [[1, 1, 3],
     [1, 2, 4],
     [1, 1, 2]]
Ainv = np.linalg.inv(A)

Ainv

array([[ 0., -1.,  2.],
       [-2.,  1.,  1.],
       [ 1., -0., -1.]])

In [9]:
A = [[1, 1, 1],
     [3, 2, 1],
     [2, 1, 2]]
Ainv = np.linalg.inv(A)

Ainv

array([[-1.50000000e+00,  5.00000000e-01,  5.00000000e-01],
       [ 2.00000000e+00,  5.55111512e-17, -1.00000000e+00],
       [ 5.00000000e-01, -5.00000000e-01,  5.00000000e-01]])